### ISSUE TITLE
Vape doesnt load 

### ISSUE THREAD

**Issue by YouDoDis** [Solar-Tweaks/Solar-Tweaks#22]
Cant run vape on this verison of solar tweaks. Vape says a minecraft forge client is needed but vape works fine on regular lunar.

**Comment by 770grappenmaker** [comment]
This is because it probably cannot find the java process, because it is a child process of `Solar Tweaks.exe` and not `Lunar Client.exe`. In my opinion, they should've known better and looked if there were any lunar client classes available, and not just assume things based on process metadata. This is not a Solar Tweaks issue but rather a vape issue. You could try if things improve if you have the regular launcher opened, but other than that, there is nothing we can do.

**Comment by 770grappenmaker** [comment]
Nevermind: I found the solution (untested) 
![image](https://user-images.githubusercontent.com/50543283/165592921-52f99c4f-5957-42ea-98e8-fe1620080be2.png)
Credits to Prorok
@YouDoDis
