### ISSUE TITLE
problem:''You must have the launcher open to login'' and ''invailed session''

### ISSUE THREAD

**Issue by zxgundam0901** [Solar-Tweaks/Solar-Tweaks#576]
I had tried opening my launcher and login in, but it still didn't work.
![image](https://user-images.githubusercontent.com/112256486/187030263-b1071796-404a-4cb1-b17d-48d35944b989.png)

**Comment by zxgundam0901** [comment]
Can someone help me???

**Comment by wusung** [comment]
You should login with your microsoft account to create the session in Lunar client first. After this, you can select the previously signed session in left-top side.

**Comment by theghoulish76** [comment]
It's not a bug. You just have to launch normal Lunar Client (only the client and not the game) and then click on sign in with Microsoft in-game in Solar Tweaks Lunar Client Minecraft. It does this because normally Lunar Client is launched in the background when you're in-game and when you try to login in-game, it launches the login pop-up through Lunar Client.
